FROM node:20-slim

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies
RUN npm ci --silent

# Copy the entire project
COPY frontend/. ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
